# Build Stage
FROM node:20-alpine AS build
WORKDIR /app
COPY coffee-roast-web/package.json coffee-roast-web/package-lock.json* ./
RUN npm install
COPY coffee-roast-web/ .
RUN npm run build

# Nginx Stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/nginx.conf

# Expose ports
EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
